# Generated by Django 4.2.5 on 2023-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_remove_productmodel_cat_delete_blog1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(default='', max_length=10)),
                ('plan', models.CharField(max_length=50)),
                ('joindate', models.DateField(max_length=40)),
                ('initialamount', models.CharField(max_length=10)),
            ],
        ),
    ]
