# Generated by Django 4.2.3 on 2023-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_addmembermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmembermodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
