# Generated by Django 4.2.3 on 2023-10-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_addmembermodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmembermodel',
            name='joindate',
            field=models.DateField(),
        ),
    ]
