# Generated by Django 4.2.3 on 2023-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_plan_delete_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
                ('joindate', models.DateField()),
            ],
        ),
    ]
