# Generated by Django 4.2.3 on 2023-11-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_gymbooking_user_gymbooking_booking_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymbooking',
            name='name',
        ),
        migrations.AlterField(
            model_name='gymbooking',
            name='booking_for',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
